- name: Create node-exporter user
  user:
    name: "{{ NODE_EXPORTER_USER | default('node-exporter') }}"
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Create node-exporter folder
  file:
    path: /opt/node-exporter
    state: directory
    owner: "{{ NODE_EXPORTER_USER | default('node-exporter') }}"
    group: "{{ NODE_EXPORTER_USER | default('node-exporter') }}"
    mode: '0755'

- name: Copy node-exporter binary
  copy:
    src: files/node_exporter
    dest: /opt/node-exporter/node_exporter
    owner: "{{ NODE_EXPORTER_USER | default('node-exporter') }}"
    group: "{{ NODE_EXPORTER_USER | default('node-exporter') }}"
    mode: '0755'

- name: Create systemd service file for node-exporter
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd to apply new service
  systemd:
    daemon_reload: yes

- name: Enable and start node-exporter service
  systemd:
    name: node-exporter
    enabled: yes
    state: started




